markdown: kramdown
layouts: ./_layouts/paraibajs
relative_permalinks: true

collections:
  meetups:
    output: true
    permalink: /meetup/:year/:title/
  talks:
    output: false
  editoras_parceiras:
    output: false
  grupos_parceiros:
    output: false

defaults:
  - scope:
      path: ""
      type: meetups
    values:
      layout: post
      passed: 0

noita:
  name: Paraiba.js
  description: Tema feito para o paraiba.js
  author:
    name: Sérgio Vilar
    url: http://sergiovilar.com.br/
  lang: pt
  stylesheets:
    - /assets/css/main.css
  menu:
    - name: Home
      url: /
    - name: Meet-ups
      url: /meetups/
    - name: Talks
      url: /talks/
    - name: Parcerias
      url: /parcerias/
    - name: Grupo no Facebook
      url: https://www.facebook.com/groups/paraibajs/
      target: _blank
    - name: Página no Facebook
      url: https://www.facebook.com/paraibajs/
      target: _blank
    - name: Github
      url: https://github.com/paraibajs/paraibajs.github.io
      target: _blank
    - name: Contas abertas
      url: https://docs.google.com/spreadsheets/d/1QxYX_3WYHJnk835vgqX9I0K2vEDRqWf2Co_3S29ZNXk/edit?usp=sharing
      target: _blank